services:
  tickers:
    container_name: tickers
    build: ./tickers
    ports:
      - "8080:8080"
    volumes:
      - ./tickers:/app
    depends_on:
      - tickers-db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    environment:
      DATABASE_URL: mongodb://root:password@tickers-db:27017
      ACCESS_TOKEN: access_token

  tickers-db:
    container_name: tickers-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./tickers-db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tickers_db

  accounts:
    container_name: accounts
    build: ./accounts
    ports:
      - "8000:8000"
    volumes:
      - ./accounts:/app
    depends_on:
      - accounts-db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: mysql+pymysql://root:password@accounts-db:3306/accounts_db
      ACCESS_TOKEN: access_token
      JWT_SECRET_KEY: secret_key
      JWT_REFRESH_SECRET_KEY: refresh_secret_key
      STRIPE_SECRET_KEY: sk_test_51MSszoKWjgNN4QwtWdoLD3Yal8VL9SXvt8GKYS7QDlLfbOPZR07zvSt7onSDOqlqyqYR1a9bsnz2R4p2inpTLbN200LfsDxGwZ
      STRIPE_PUBLISHABLE_KEY: pk_test_51MSszoKWjgNN4QwtX7YtYxwm7wdGNEsNkWn6tMJAwlfF5ohvg9k6ejOh0WMmMA7QL0N434RSLJigifJFIANUF2Ku00w7eFgwQm

  accounts-db:
    container_name: accounts-db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./accounts-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: accounts_db
