FROM python:3.11

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
RUN env

RUN pip install --no-cache pipenv

COPY Pipfile .
COPY Pipfile.lock .
RUN pipenv install --system --deploy

WORKDIR /app

COPY . .

CMD ["celery", "-A", "app.main.celery_app", "worker", "--loglevel=info"]
