version: "3.8"

services:
  postgres:
    container_name: accounts-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: accounts
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  accounts:
    container_name: accounts-app
    build:
      context: accounts/
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    ports:
      - 5000:5000
    environment:
      env_file: ./accounts/system_configs/.env
    volumes:
      - ./accounts/:/app
    depends_on:
      - postgres

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --api-key sk_test_51MSszoKWjgNN4QwtWdoLD3Yal8VL9SXvt8GKYS7QDlLfbOPZR07zvSt7onSDOqlqyqYR1a9bsnz2R4p2inpTLbN200LfsDxGwZ --forward-to accounts-app:5000/payment/webhook --skip-verify
    env_file: ./accounts/system_configs/.env

  mongo:
    container_name: tickers-db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      env_file: ./tickers/system_configs/.env
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  tickers:
    container_name: tickers-app
    build:
      context: tickers/
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    ports:
      - 8000:8000
    environment:
      env_file: ./tickers/system_configs/.env
    volumes:
      - ./tickers/:/app
    depends_on:
      - mongo

  celery:
    container_name: tickers-celery
    build:
      context: tickers/
      dockerfile: Dockerfile.worker
    environment:
      env_file: ./tickers/system_configs/.env
    volumes:
      - ./tickers/:/app
    depends_on:
      - mongo
      - rabbitmq
