FROM python:3.11

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYROOT /pyroot
ENV PYTHONUSERBASE $PYROOT
RUN env

RUN pip install --no-cache pipenv

COPY Pipfile .
COPY Pipfile.lock .
RUN PIP_USER=1 PIP_IGNORE_INSTALLED=1 pipenv install --system --deploy

WORKDIR /app

COPY . .

CMD ["celery", "-A", "app.worker.celery.app", "worker", "--loglevel=info"]
